invest_company_dict = {
 "AAPL":[
    "Vanguard Group Inc.",
    "BlackRock Inc.",
    "State Street Corporation",
    "Fidelity Investments",
    "Geode Capital Management",
    "Berkshire Hathaway Inc.",
    "T. Rowe Price Associates",
    "JPMorgan Chase",
    "Eaton Vance Management",
    "BlackRock Life Ltd.",
    "T. Rowe Price International Ltd.",
    "JPMorgan Investment Management, Inc.",
    "Northern Trust Corporation",
    "Bank of New York Mellon Corporation",
    "Invesco Ltd.",
    "Bank of America Corp.",
    "Morgan Stanley",
    "Goldman Sachs Group Inc.",
    "Wells Fargo",
    "Norges Bank Investment Management",
    "CalPERS",
    "Bridgewater Associates",
    "Tiger Global Management",
    "JANA Partners LLC",
    "ValueAct Capital",
    "Janus Henderson Group PLC",
    "State Farm Mutual Automobile Insurance Co.",
    "Arrowstreet Capital LP",
    "Geode Capital Management LLC",
    "GAMMA Investing LLC",
    "Modus Advisors LLC",
    "WCM Investment Management LLC",
    "Nuveen LLC",
    "TIAA-CREF Funds",
    "Amundi",
    "Mitsubishi UFJ Kokusai Asset Management Co.",
    "Bank of Montreal",
    "Citigroup",
    "Vanguard Total Stock Market Index Fund",
    "Arrowstreet Capital",
    "UBS Asset Management",
    "MFS Investment Management",
    "Massachusetts Financial Services",
    "Jackson National Asset Management",
    "Schroders PLC",
    "Swedbank AB",
    "Assenagon Asset Management SA",
    "Union Investment Luxembourg",
    "LPL Financial LLC",
    "Manulife Financial Corp.",
    "Fayez Sarofim",
    "SG Americas Securities LLC",
    "CI Financial Corp.",
    "Neuberger Berman Group LLC",
    "Voya Investment Management",
    "Aberdeen",
    "National Bank of Canada",
    "BNP Paribas SA",
    "DZ Bank AG Deutsche Zentral-Genossenschaftsbank"
],
"XOM":[
  "The Vanguard Group, Inc.",
  "BlackRock Institutional Trust Company, N.A.",
  "State Street Global Advisors (US)",
  "Fidelity Management & Research Company LLC",
  "Geode Capital Management, L.L.C.",
  "Norges Bank Investment Management (NBIM)",
  "JP Morgan Asset Management",
  "Managed Account Advisors LLC",
  "T. Rowe Price Associates, Inc.",
  "Morgan Stanley Smith Barney LLC",
  "BofA Global Research (US)",
  "Capital Research Global Investors",
  "Northern Trust Investments, Inc.",
  "Dimensional Fund Advisors, L.P.",
  "Charles Schwab Investment Management, Inc.",
  "State Farm Insurance Companies",
  "Fisher Investments",
  "Wellington Management Company, LLP",
  "BlackRock Asset Management Ireland Limited",
  "Columbia Threadneedle Investments (US)",
  "Capital International Investors",
  "Amundi Asset Management, SAS",
  "Mellon Investments Corporation",
  "Fidelity Institutional Asset Management",
  "Nuveen LLC",
  "Parametric Portfolio Associates LLC",
  "MFS Investment Management",
  "Legal & General Investment Management Ltd.",
  "Putnam Investment Management, L.L.C.",
  "Franklin Advisers, Inc.",
  "JPMorgan Private Bank (United States)",
  "UBS Financial Services, Inc.",
  "Goldman Sachs Asset Management, L.P.",
  "J.P. Morgan Securities LLC",
  "BlackRock Investment Management (UK) Ltd.",
  "Schweizerische Nationalbank",
  "Wells Fargo Advisors",
  "Sumitomo Mitsui Trust Bank, Limited",
  "Morgan Stanley & Co. LLC",
  "GQG Partners, LLC",
  "BNY Mellon Asset Management",
  "Fayez Sarofim & Co.",
  "Invesco Capital Management LLC",
  "BlackRock Financial Management, Inc.",
  "RBC Capital Markets Wealth Management",
  "First Eagle Investment Management, L.L.C.",
  "National Pension Service",
  "BNP Paribas Securities Corp. North America",
  "Invesco Advisers, Inc.",
  "California Public Employees' Retirement System",
  "PNC Investments LLC",
  "Hightower Advisors, LLC",
  "Goldman Sachs & Company, Inc.",
  "BNY Wealth",
  "American Century Investment Management, Inc.",
  "AllianceBernstein L.P.",
  "Mitsubishi UFJ Asset Management Co., Ltd.",
  "BlackRock Investment Management, LLC",
  "Rhumbline Advisers Ltd. Partnership",
  "Northern Trust Global Investments"
],
"JPM":[
  "The Vanguard Group, Inc.",
  "BlackRock Institutional Trust Company, N.A.",
  "State Street Global Advisors (US)",
  "Geode Capital Management, L.L.C.",
  "Fidelity Management & Research Company LLC",
  "Morgan Stanley Smith Barney LLC",
  "Norges Bank Investment Management (NBIM)",
  "Capital International Investors",
  "BofA Global Research (US)",
  "Capital World Investors",
  "T. Rowe Price Associates, Inc.",
  "Wellington Management Company, LLP",
  "Managed Account Advisors LLC",
  "Columbia Threadneedle Investments (US)",
  "Capital Research Global Investors",
  "Northern Trust Investments, Inc.",
  "UBS Financial Services, Inc.",
  "BlackRock Asset Management Ireland Limited",
  "Dimensional Fund Advisors, L.P.",
  "Wells Fargo Advisors",
  "Charles Schwab Investment Management, Inc.",
  "Legal & General Investment Management Ltd.",
  "Fisher Investments",
  "MFS Investment Management",
  "Parametric Portfolio Associates LLC",
  "Goldman Sachs Asset Management, L.P.",
  "Nuveen LLC",
  "BlackRock Investment Management (UK) Ltd.",
  "Mellon Investments Corporation",
  "BlackRock Financial Management, Inc.",
  "Morgan Stanley & Co. LLC",
  "Raymond James & Associates, Inc.",
  "Neuberger Berman, LLC",
  "Sanders Capital, LLC",
  "Northern Trust Global Investments",
  "BlackRock (Netherlands) B.V.",
  "Boston Partners",
  "Dimon (James)",
  "Barclays Bank PLC",
  "Envestnet Asset Management, Inc.",
  "Invesco Advisers, Inc.",
  "RBC Capital Markets Wealth Management",
  "Sumitomo Mitsui Trust Bank, Limited",
  "BNY Mellon Asset Management",
  "Union Investment Privatfonds GmbH",
  "ClearBridge Investments, LLC",
  "HSBC Global Asset Management (UK) Limited",
  "UBS Asset Management (Americas) LLC",
  "Invesco Capital Management LLC",
  "California Public Employees' Retirement System",
  "RBC Dominion Securities, Inc.",
  "PNC Investments LLC",
  "AllianceBernstein L.P.",
  "UBS Asset Management (UK) Ltd.",
  "Bessemer Trust Company, N.A. (US)",
  "Principal Global Investors (Equity)",
  "Aperio Group, LLC",
  "BlackRock Japan Co., Ltd.",
  "Citi Investment Research (US)",
  "National Pension Service"
],
"JNJ":[
  "The Vanguard Group, Inc.",
  "State Street Global Advisors (US)",
  "BlackRock Institutional Trust Company, N.A.",
  "Geode Capital Management, L.L.C.",
  "JP Morgan Asset Management",
  "State Farm Insurance Companies",
  "Norges Bank Investment Management (NBIM)",
  "Morgan Stanley Smith Barney LLC",
  "Wellington Management Company, LLP",
  "BlackRock Asset Management Ireland Limited",
  "Charles Schwab Investment Management, Inc.",
  "Northern Trust Investments, Inc.",
  "Legal & General Investment Management Ltd.",
  "MFS Investment Management",
  "BlackRock Investment Management (UK) Ltd.",
  "Dimensional Fund Advisors, L.P.",
  "BofA Global Research (US)",
  "Wells Fargo Advisors",
  "Franklin Advisers, Inc.",
  "Columbia Threadneedle Investments (US)",
  "Fidelity Management & Research Company LLC",
  "Parametric Portfolio Associates LLC",
  "Managed Account Advisors LLC",
  "Mellon Investments Corporation",
  "UBS Financial Services, Inc.",
  "Amundi Asset Management, SAS",
  "Invesco Capital Management LLC",
  "Invesco Advisers, Inc.",
  "Goldman Sachs Asset Management, L.P.",
  "HSBC Global Asset Management (UK) Limited",
  "BlackRock Financial Management, Inc.",
  "Nuveen LLC",
  "AllianceBernstein L.P.",
  "Janus Henderson Investors",
  "Journey Strategic Wealth LLC",
  "Ninety One UK Limited",
  "Grantham Mayo Van Otterloo & Co LLC",
  "Schweizerische Nationalbank",
  "DWS Investments UK Limited",
  "American Century Investment Management, Inc.",
  "T. Rowe Price Associates, Inc.",
  "JPMorgan Private Bank (United States)",
  "Raymond James & Associates, Inc.",
  "Flossbach von Storch AG",
  "Nordea Funds Oy",
  "Morgan Stanley & Co. LLC",
  "Sumitomo Mitsui Trust Bank, Limited",
  "DWS Investment GmbH",
  "ClearBridge Investments, LLC",
  "BlackRock (Netherlands) B.V.",
  "UBS Asset Management (UK) Ltd.",
  "BNY Mellon Asset Management",
  "BlackRock Investment Management, LLC",
  "Independent Franchise Partners LLP",
  "AQR Capital Management, LLC",
  "Northern Trust Global Investments",
  "National Pension Service",
  "RBC Dominion Securities, Inc."
],
"Meta":[
  "The Vanguard Group, Inc.",
  "Fidelity Management & Research Company LLC",
  "BlackRock Institutional Trust Company, N.A.",
  "State Street Global Advisors (US)",
  "Geode Capital Management, L.L.C.",
  "Capital World Investors",
  "T. Rowe Price Associates, Inc.",
  "JP Morgan Asset Management",
  "Capital Research Global Investors",
  "Norges Bank Investment Management (NBIM)",
  "Capital International Investors",
  "Invesco Capital Management (QQQ Trust)",
  "BlackRock Asset Management Ireland Limited",
  "Northern Trust Investments, Inc.",
  "Charles Schwab Investment Management, Inc.",
  "AllianceBernstein L.P.",
  "Nuveen LLC",
  "Legal & General Investment Management Ltd.",
  "Jennison Associates LLC",
  "Mellon Investments Corporation",
  "Schweizerische Nationalbank",
  "Fisher Investments",
  "Wells Fargo Advisors",
  "BlackRock Investment Management, LLC",
  "Sumitomo Mitsui Trust Bank, Limited",
  "American Century Investment Management, Inc.",
  "Morgan Stanley & Co. LLC",
  "ClearBridge Investments, LLC",
  "Baillie Gifford & Co.",
  "California Public Employees' Retirement System",
  "Franklin Advisers, Inc.",
  "Morgan Stanley Investment Management Inc. (US)",
  "Fidelity Institutional Asset Management",
  "Barclays Bank PLC",
  "UBS Asset Management (UK) Ltd.",
  "UBS Asset Management (Switzerland)",
  "HSBC Global Asset Management (UK) Limited",
  "National Pension Service"
]

}
